### ISSUE TITLE
Add endpoints for Coinmarketcap to poll total stSOL supply

### ISSUE THREAD

**Issue by ruuda** [ChorusOne/solido#150]
Many intergrations rely on Coinmarketcap for data. It has a request form to get a token listed here:

https://support.coinmarketcap.com/hc/en-us/requests/new?ticket_form_id=360000493112

### Manual implementation

It asks for two http endpoints that return a numeric string with the total supply and circulating supply. It would not be hard to add such endpoints to the maintenance daemon. We could then run a reverse proxy to expose just these endpoints publicly on the internet, but keep the `/metrics` endpoint private. (We could even make most of the metrics public, as they are reporting public on-chain data anyway.) See also https://github.com/ChorusOne/solido/issues/96.

### Relying on SPL-token

stSOL is an SPL token. Doesn’t some server exist already, with an endpoint that takes the token mint address as query parameter, and reports the supply in the format that Coinmarketcap wants?

**Comment by hritique** [comment]
The endpoint is live at https://solana-dev.testnet.lido.fi/api/stsol?q=totalcoins & https://solana-dev.testnet.lido.fi/api/stsol?q=circulating

**Comment by ruuda** [comment]
The endpoint exists, this is done.
