### ISSUE TITLE
Resolve `cargo audit` issues

### ISSUE THREAD

**Issue by ruuda** [ChorusOne/solido#358]
I just ran `cargo-audit`, and we do depend on a few libraries that have known security vulnerabilities. Some could in theory affect how the CLI connects to the RPC, so if you connect to a public RPC instead of your own validator node, then this might be a problem. I don’t know if it is in practice, but it’s easier to just update.

Some other issues pointed out by it are not relevant to us, but still, if `cargo audit` reporting issues scares auditors, it’s easier to just resolve these issues, than to figure out if they are actually a problem for us.

We should also run `cargo audit` on CI in some for or another. On the one hand, I don’t like that external things can break our build. But on the other hand, I don’t know of a better way to do this at the moment. We do have “Dependabot alerts — Receive alerts of new vulnerabilities that affect your dependencies.” enabled in the repository security settings, and I just turned on “Dependabot security updates — Easily upgrade to non-vulnerable dependencies.” as well. (I hope it’s not as spammy as the regular dependabot.) But so far these haven’t reported anything, so apparently they don’t check all the things that `cargo audit` checks.

**Comment by glottologist** [comment]
That is frustrating.

**Comment by glottologist** [comment]
@ruuda  Maybe it is better to split this ticket in two:
1. Resolve audit issues (as we can then proceed with the Kudelski audit
2. Run cargo audit on CI (which we can fix after 1)

**Comment by ruuda** [comment]
Yes, let’s make this ticket about resolving the existing reports then, and we can make a new one for running it on CI. I am updating our dependencies now (including the multisig program). This should also fix #294.

> If we switch the building into a/the container we can support cargo audit.

I don’t understand what containers have to do with this. We can install `cargo audit` on CI and run it, we install a few others tools that way already. It doesn’t care about whether it is inside or outside a container.

**Comment by glottologist** [comment]
Sorry I misunderstood your comment regarding ```Cargo.lock```, ignore it!

**Comment by ruuda** [comment]
Ah, I meant, GitHub does not support scanning dependencies for Rust at all, but I wrote `Cargo.lock` to distinguish it from other package managers. Sorry for the confusion!

**Comment by ruuda** [comment]
Fixed by #359.
