### ISSUE TITLE
Retry transaction to unstake from inactive validator

### ISSUE THREAD

**Issue by enriquefynn** [ChorusOne/solido#386]
If for some reason Solana doesn't let us unstake the full amount a validator has, the transaction should be repeated with a lower value, maybe exponentially diminish the unstake amount until it passes.

**Comment by ruuda** [comment]
Why wouldn’t Solana let us unstake the full amount? It might take more than one epoch to deactivate, but the transaction shouldn’t fail, should it?

**Comment by enriquefynn** [comment]
Yeah, I think it shouldn't. I understood the mechanism wrong 😅
