### ISSUE TITLE
[Anchor] Deposit/Withdraw

### ISSUE THREAD

**Issue by enriquefynn** [ChorusOne/solido#444]
Main issue: #438
Following the [anchor-integration](https://github.com/ChorusOne/solido/tree/anchor-integration) branch.

## Deposit / Withdraw
- Users should be able to deposit stSOL and get bSOL in return.
- Keep user's shares of the pool based on the amount of bSOL they have. bSOL tokens can be abstracted in shares and calculated on-the-fly if they can be not pegged 1:1 with SOL.
- To withdraw, users burn bSOL and get stSOL in return.
- Keep exchange rate similar to lido's to calculate amount to be withdrawn

**Comment by ruuda** [comment]
Both deposit (#446) and withdraw (#460) are now implemented.
