### ISSUE TITLE
[Anchor] Record statistics about deposits and withdrawals

### ISSUE THREAD

**Issue by ruuda** [ChorusOne/solido#450]
In Solido we keep a histogram of deposits. This is quite useful, we should do the same for Anker. We may need to generalize the histogram over the token type then.

**Comment by ruuda** [comment]
The counters were added in https://github.com/ChorusOne/solido/pull/556. This is not yet exposed to Prometheus though.

**Comment by enriquefynn** [comment]
Can you check this PR: #561 😬
