### ISSUE TITLE
[Anchor] Make the rewards address configurable

### ISSUE THREAD

**Issue by ruuda** [ChorusOne/solido#457]
The `ClaimRewards` function will need to send the rewards somewhere, through Wormhole. We may need to change this address in the future. To avoid a hassle at that time, where we have to upgrade the program, we can make the address configurable now. For this we will need to add two addresses to the state:

* The rewards address (a Terra address, not a Solana address! But maybe we need to use a particular Solana address at a program-derived address with the Terra address as seed, not sure about this, we need to check the Wormhole docs).
* A manager address, which we should set to the multisig. Or maybe we could avoid the need for a manager, and use Solido's manager instead. We already have a reference to the Solido instance, so we can read the manager from there to confirm. But I think it’s safer to just store it in the Anker instance to make it more independent.

We will also need a function to change the rewards address, which can only be called by the manager. And we will need to pass in the manager at initialization.

**Comment by ruuda** [comment]
Implementation in progress in #472.

**Comment by enriquefynn** [comment]
Closed by #472
