### ISSUE TITLE
[Anchor] Make maintenance bot call ClaimRewards on Anker instance

### ISSUE THREAD

**Issue by ruuda** [ChorusOne/solido#459]
We have the maintenance bot that submits maintenance transactions for Solido. Once the Anchor integration is ready, something needs to periodically call `ClaimRewards` if the value of the reserve in SOL exceeds the bSOL supply. The existing maintenance bot could do this; it would already watch the Anker instance for #458, so we can also make it submit the `ClaimRewards` transaction if it notices there are rewards to claim.

**Comment by enriquefynn** [comment]
We split the `ClaimRewards` into `SellRewards` and `SendRewards`.
Selling rewards is being implemented in #480.

**Comment by ruuda** [comment]
This has been implemented in #480 and #481.
