### ISSUE TITLE
[Anker] Token's swap pool order should not matter

### ISSUE THREAD

**Issue by enriquefynn** [ChorusOne/solido#468]
Currently, token a and b order matters for the swap (performed by the `SellRewards`).
This shouldn't be the case, since we can inspect the token's minter and decide which one is the UST/stSOL.

**Comment by ruuda** [comment]
I think it’s fine to hard-code, if we know in advance which is which. It does make the ability to change the pool less useful though, as it puts requirements on the token order of the pool. So maybe we should allow both orders and figure it out at runtime yeah. :+1:
