### ISSUE TITLE
Backfilling historical stSOL price information

### ISSUE THREAD

**Issue by ruuda** [ChorusOne/solido#514]
In #513 we are introducing a new small daemon that stores the stSOL price in a database, and exposes an http endpoint to compute APY over a given time period.

The way in which we fetch the price is based on reading the current state of accounts from an RPC node, this can’t get historical data.

However, we could still get historical prices by looking for older `Deposit` transactions: those establish an exchange rate. We could do this in an external script even, as long as we can get the data into the same database. Then this service would be able to return the APY even for times when it wasn’t yet collecting data.

**Comment by ruuda** [comment]
Pavel at P2P has kindly provided us with a list of historical Solido interactions extracted from the chain, in the following format:

```csv
epoch,transaction,slot,blocktime,SOL_deposited,stSOL_minted
221,2t2g6FyGN4WnWwCLcRTuHRn66NaEJTWJy4vo1yxpSeDeWuYM9foHSP6HXxMVhBiSoo8UbS1P7kkxrdMJi2SXQkPf,95592492,1631120798,5.1788,5.1788
221,2mYUcFAw8ztT6mpHrPtQ9TKuwEGyvw26agS5VVkHHjviHN6AJE2Jq5jp3camCkEbf1b8SQ2LMDgfixnwaVfSAA7s,95592924,1631121028,1.25,1.25
232,5w9bk4ixB2VajA2a4JvvVJr774WFDUZPKSaGjd3QxtpiYDRaqTPs9Az85d245cbQijjQ6B2AZtxEpzZpmATKm6kW,100242837,1633634648,40.7,40.565090943
```
In principle all this information is public, but I’m not sure if it’s a good idea to share the full list here, so I’ll keep it on my machine for now.

Now the only thing left to do is to write a small script to insert this into the database. We also need timestamps, we can get them from the stake-weighted median timestamp of the block. These timestamps cannot be trusted due to https://github.com/solana-labs/solana/issues/18992, but it’s the only thing we have right now, so it will have to do.

CC @enriquefynn you might be interested in this

**Comment by enriquefynn** [comment]
Great!
I just created a [small script](https://gist.github.com/enriquefynn/5fcb7f14289597b2ce51d20150700a38) to populate a database with these values
It is creating one data point for each line. But we could also aggregate it.

**Comment by ruuda** [comment]
Done, see @enriquefynn’s script above.
