### ISSUE TITLE
wrong minimum_balance in get_reserve_available_balance()

### ISSUE THREAD

**Issue by kkonevets** [ChorusOne/solido#546]
Hi! Please excuse me if I am wrong, but why do you use
```rust
let minimum_balance = Lamports(rent.minimum_balance(0));
```
instead of 
```rust
let minimum_balance = Lamports(rent.minimum_balance(reserve_account.data_len()));
```
in [here](https://github.com/ChorusOne/solido/blob/74181c9517ae9faa5516faafe8b433c1306182b1/program/src/logic.rs#L82)?

The point is to get the minimum rent for the reserve account to be alive. And the `reserve_account.data_len()` could be non zero.

**Comment by ruuda** [comment]
The reserve account doesn’t store any data, it only holds SOL, that’s why it’s `data_len()` is 0.

**Comment by kkonevets** [comment]
Thanks
