### ISSUE TITLE
Penalty distribution and insurance

### ISSUE THREAD

**Issue by ruuda** [ChorusOne/solido#85]
## Background

At the moment, we expect the SOL balance of the stake pool to only go *up* through external modifications (so excluding deposits and withdrawals). At the moment these external modifications are only reward payments. However, at some point we may need to deal with penalties, and the SOL balance might go *down*.

## Current approach

Currently, [the stake pool performs a saturating subtract](https://github.com/solana-labs/solana-program-library/blob/26560daae234bc3e00c08a2f2c8d81d1c2f41498/stake-pool/program/src/processor.rs#L1414
), which means it always computes a non-negative fee. If the SOL balance did in fact go down, no fees in stake pool tokens will be minted, but no *negative* rewards will be minted either. This means the loss is implicitly socialized over all stake pool token holders.

## Proposal

In Lido we have an insurance account that part of the fees get paid into (when they are positive). At first I thought the stake pool should support negative fees, and then in Lido we could make a case distinction: credit to the fee accounts (treasury, insurance, etc.) if the fee was positive, but debit only from the insurance account when it was negative.

But aside from complications representing negative amounts as SPL tokens, this would not make up for the full loss, only for the fee percentage. For example, if the stake pool fee was configured to be 10%, then Lido could only compensate stSOL holders for 10% of the loss.

What we should probably do instead, is have a separate instruction for this case, where we burn tokens from the insurance fund equivalent in value to the lost SOL. (And if the insurance balance is insufficient, the remaining loss gets socialized.)

**Comment by malikankit** [comment]
Closing it. If slashing is re-implemented, let's re-open it.
